apiVersion: skaffold/v4beta6
kind: Config
build:
  local:
    push: false
  artifacts:
  - image: bert
    context: bert
  - image: ernie
    context: ernie
deploy:
  docker:
    images: [bert, ernie]
portForward:
- resourceType: container
  resourceName: bert
  port: 8080
  localPort: 9000
- resourceType: container
  resourceName: ernie
  port: 8081
  localPort: 9001
